/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VerifyFilenameRouteImport } from './routes/verify/$filename'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminJudgementsIndexRouteImport } from './routes/admin/judgements/index'
import { Route as AdminAssignmentIndexRouteImport } from './routes/admin/assignment/index'
import { Route as ApiJudgementsFilenameRouteImport } from './routes/api/judgements/$filename'
import { Route as ApiJudgementsSplatRouteImport } from './routes/api/judgements/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssignmentSplatRouteImport } from './routes/api/assignment/$'
import { Route as AdminJudgementsFilenameRouteImport } from './routes/admin/judgements/$filename'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyFilenameRoute = VerifyFilenameRouteImport.update({
  id: '/verify/$filename',
  path: '/verify/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJudgementsIndexRoute = AdminJudgementsIndexRouteImport.update({
  id: '/admin/judgements/',
  path: '/admin/judgements/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssignmentIndexRoute = AdminAssignmentIndexRouteImport.update({
  id: '/admin/assignment/',
  path: '/admin/assignment/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJudgementsFilenameRoute = ApiJudgementsFilenameRouteImport.update({
  id: '/api/judgements/$filename',
  path: '/api/judgements/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJudgementsSplatRoute = ApiJudgementsSplatRouteImport.update({
  id: '/api/judgements/$',
  path: '/api/judgements/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssignmentSplatRoute = ApiAssignmentSplatRouteImport.update({
  id: '/api/assignment/$',
  path: '/api/assignment/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJudgementsFilenameRoute = AdminJudgementsFilenameRouteImport.update({
  id: '/admin/judgements/$filename',
  path: '/admin/judgements/$filename',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/verify/$filename': typeof VerifyFilenameRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/judgements/$filename': typeof AdminJudgementsFilenameRoute
  '/api/assignment/$': typeof ApiAssignmentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/judgements/$': typeof ApiJudgementsSplatRoute
  '/api/judgements/$filename': typeof ApiJudgementsFilenameRoute
  '/admin/assignment/': typeof AdminAssignmentIndexRoute
  '/admin/judgements/': typeof AdminJudgementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/verify/$filename': typeof VerifyFilenameRoute
  '/admin': typeof AdminIndexRoute
  '/admin/judgements/$filename': typeof AdminJudgementsFilenameRoute
  '/api/assignment/$': typeof ApiAssignmentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/judgements/$': typeof ApiJudgementsSplatRoute
  '/api/judgements/$filename': typeof ApiJudgementsFilenameRoute
  '/admin/assignment': typeof AdminAssignmentIndexRoute
  '/admin/judgements': typeof AdminJudgementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/users': typeof AdminUsersRoute
  '/verify/$filename': typeof VerifyFilenameRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/judgements/$filename': typeof AdminJudgementsFilenameRoute
  '/api/assignment/$': typeof ApiAssignmentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/judgements/$': typeof ApiJudgementsSplatRoute
  '/api/judgements/$filename': typeof ApiJudgementsFilenameRoute
  '/admin/assignment/': typeof AdminAssignmentIndexRoute
  '/admin/judgements/': typeof AdminJudgementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/users'
    | '/verify/$filename'
    | '/admin/'
    | '/admin/judgements/$filename'
    | '/api/assignment/$'
    | '/api/auth/$'
    | '/api/judgements/$'
    | '/api/judgements/$filename'
    | '/admin/assignment/'
    | '/admin/judgements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/users'
    | '/verify/$filename'
    | '/admin'
    | '/admin/judgements/$filename'
    | '/api/assignment/$'
    | '/api/auth/$'
    | '/api/judgements/$'
    | '/api/judgements/$filename'
    | '/admin/assignment'
    | '/admin/judgements'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/users'
    | '/verify/$filename'
    | '/admin/'
    | '/admin/judgements/$filename'
    | '/api/assignment/$'
    | '/api/auth/$'
    | '/api/judgements/$'
    | '/api/judgements/$filename'
    | '/admin/assignment/'
    | '/admin/judgements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminUsersRoute: typeof AdminUsersRoute
  VerifyFilenameRoute: typeof VerifyFilenameRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminJudgementsFilenameRoute: typeof AdminJudgementsFilenameRoute
  ApiAssignmentSplatRoute: typeof ApiAssignmentSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiJudgementsSplatRoute: typeof ApiJudgementsSplatRoute
  ApiJudgementsFilenameRoute: typeof ApiJudgementsFilenameRoute
  AdminAssignmentIndexRoute: typeof AdminAssignmentIndexRoute
  AdminJudgementsIndexRoute: typeof AdminJudgementsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$filename': {
      id: '/verify/$filename'
      path: '/verify/$filename'
      fullPath: '/verify/$filename'
      preLoaderRoute: typeof VerifyFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/judgements/': {
      id: '/admin/judgements/'
      path: '/admin/judgements'
      fullPath: '/admin/judgements/'
      preLoaderRoute: typeof AdminJudgementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assignment/': {
      id: '/admin/assignment/'
      path: '/admin/assignment'
      fullPath: '/admin/assignment/'
      preLoaderRoute: typeof AdminAssignmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/judgements/$filename': {
      id: '/api/judgements/$filename'
      path: '/api/judgements/$filename'
      fullPath: '/api/judgements/$filename'
      preLoaderRoute: typeof ApiJudgementsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/judgements/$': {
      id: '/api/judgements/$'
      path: '/api/judgements/$'
      fullPath: '/api/judgements/$'
      preLoaderRoute: typeof ApiJudgementsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assignment/$': {
      id: '/api/assignment/$'
      path: '/api/assignment/$'
      fullPath: '/api/assignment/$'
      preLoaderRoute: typeof ApiAssignmentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/judgements/$filename': {
      id: '/admin/judgements/$filename'
      path: '/admin/judgements/$filename'
      fullPath: '/admin/judgements/$filename'
      preLoaderRoute: typeof AdminJudgementsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminUsersRoute: AdminUsersRoute,
  VerifyFilenameRoute: VerifyFilenameRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminJudgementsFilenameRoute: AdminJudgementsFilenameRoute,
  ApiAssignmentSplatRoute: ApiAssignmentSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiJudgementsSplatRoute: ApiJudgementsSplatRoute,
  ApiJudgementsFilenameRoute: ApiJudgementsFilenameRoute,
  AdminAssignmentIndexRoute: AdminAssignmentIndexRoute,
  AdminJudgementsIndexRoute: AdminJudgementsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
